# Generated by Django 5.2.3 on 2025-06-14 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название здания')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('area', models.CharField(blank=True, max_length=200, null=True, verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
                'unique_together': {('name', 'address')},
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.CharField(max_length=100, unique=True, verbose_name='ID объекта')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('display_address', models.TextField(verbose_name='Адрес для отображения')),
                ('bedrooms', models.IntegerField(blank=True, null=True, verbose_name='Спальни')),
                ('bathrooms', models.IntegerField(blank=True, null=True, verbose_name='Ванные')),
                ('area_sqft', models.FloatField(blank=True, null=True, verbose_name='Площадь (кв.фт)')),
                ('area_sqm', models.FloatField(blank=True, null=True, verbose_name='Площадь (кв.м)')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Цена')),
                ('price_currency', models.CharField(default='AED', max_length=10, verbose_name='Валюта')),
                ('price_duration', models.CharField(choices=[('sell', 'Продажа'), ('rent', 'Аренда')], max_length=10, verbose_name='Тип цены')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('agent_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Имя агента')),
                ('agent_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон агента')),
                ('broker_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Брокер')),
                ('broker_license', models.CharField(blank=True, max_length=100, null=True, verbose_name='Лицензия брокера')),
                ('property_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип недвижимости')),
                ('furnishing', models.CharField(blank=True, max_length=50, null=True, verbose_name='Меблировка')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='Референс')),
                ('rera_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='RERA номер')),
                ('added_on', models.DateTimeField(blank=True, null=True, verbose_name='Дата добавления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='Особенности')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='Изображения')),
                ('roi', models.FloatField(blank=True, null=True, verbose_name='ROI (%)')),
                ('days_on_market', models.IntegerField(blank=True, null=True, verbose_name='Дней на рынке')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('area', models.CharField(max_length=200, verbose_name='Район')),
                ('avg_sale_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Средняя цена продажи')),
                ('avg_rent_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Средняя цена аренды')),
                ('total_sale_listings', models.IntegerField(verbose_name='Объявлений на продажу')),
                ('total_rent_listings', models.IntegerField(verbose_name='Объявлений на аренду')),
                ('avg_days_on_market', models.FloatField(verbose_name='Средние дни на рынке')),
            ],
            options={
                'verbose_name': 'Аналитика',
                'verbose_name_plural': 'Аналитика',
                'unique_together': {('date', 'area')},
            },
        ),
    ]
