# Generated by Django 5.2.3 on 2025-06-14 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roi', models.FloatField(blank=True, null=True, verbose_name='ROI объявления (%)')),
                ('price_per_sqft', models.FloatField(blank=True, null=True, verbose_name='Цена за кв.фт')),
                ('building_avg_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Средняя цена в здании')),
                ('building_avg_price_by_bedrooms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Средняя цена в здании для данного кол-ва спален')),
                ('building_avg_roi', models.FloatField(blank=True, null=True, verbose_name='Средний ROI здания (%)')),
                ('building_avg_exposure_days', models.FloatField(blank=True, null=True, verbose_name='Средняя экспозиция здания (дни)')),
                ('building_sale_count', models.IntegerField(default=0, verbose_name='Объявлений на продажу в здании')),
                ('building_rent_count', models.IntegerField(default=0, verbose_name='Объявлений на аренду в здании')),
                ('building_sale_count_by_bedrooms', models.IntegerField(default=0, verbose_name='Объявлений на продажу в здании с таким же кол-вом спален')),
                ('building_rent_count_by_bedrooms', models.IntegerField(default=0, verbose_name='Объявлений на аренду в здании с таким же кол-вом спален')),
                ('area_avg_days_on_market', models.FloatField(blank=True, null=True, verbose_name='Средняя экспозиция района (дни)')),
                ('avg_rent_by_bedrooms', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Средняя аренда в здании для данного кол-ва спален')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='properties.property', verbose_name='Объект недвижимости')),
            ],
            options={
                'verbose_name': 'Метрики недвижимости',
                'verbose_name_plural': 'Метрики недвижимости',
                'indexes': [models.Index(fields=['roi'], name='properties__roi_da044a_idx'), models.Index(fields=['building_avg_roi'], name='properties__buildin_ee65b1_idx'), models.Index(fields=['price_per_sqft'], name='properties__price_p_49f225_idx'), models.Index(fields=['building_avg_exposure_days'], name='properties__buildin_a77d01_idx'), models.Index(fields=['area_avg_days_on_market'], name='properties__area_av_a4e5be_idx')],
            },
        ),
    ]
