# Generated by Django 5.1.7 on 2025-09-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_propertymetrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='Ссылка'),
        ),
    ]
