# Generated by Django 5.1.7 on 2025-09-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='agent_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Имя агента'),
        ),
        migrations.AlterField(
            model_name='property',
            name='broker_name',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Брокер'),
        ),
    ]
